"""empty message

Revision ID: 29b52d93c3d1
Revises: e78eeb14217a
Create Date: 2019-07-22 16:42:19.596306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29b52d93c3d1'
down_revision = 'e78eeb14217a'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('users_dos',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('email', sa.String(length=45), nullable=False),
    # sa.Column('password', sa.String(length=45), nullable=False),
    # sa.Column('registered_on', sa.DateTime(), nullable=False),
    # sa.Column('admin', sa.Boolean(), nullable=False),
    # sa.Column('confirmed', sa.Boolean(), nullable=False),
    # sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email')
    # )
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('users_dos')
    # ### end Alembic commands ###
