"""empty message

Revision ID: e78eeb14217a
Revises: 
Create Date: 2019-07-22 14:45:10.729712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e78eeb14217a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('nid', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('registered_on', mysql.DATETIME, nullable=False, default=False),
    sa.Column('admin', mysql.BOOLEAN, nullable=False, default=False),
    sa.Column('confirmed', mysql.BOOLEAN, nullable=False, default=False),
    sa.Column('confirmed_on', mysql.DATETIME, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
